baseURL: https://lixiang.dev
languageCode: en-us
defaultContentLanguage: en
title: LIX
googleAnalytics: G-TYYMZPT8H6

outputs:
home:
- html
- json
- rss

privacy:
  disqus:
    disable: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

# To disable, set to an extremely large value, such as 999999
pagination:
  pagerSize: 5

# See the list of emoji shortcodes for available emoticons.
# https://gohugo.io/quick-reference/emojis/
enableEmoji: true

params:
  homeMetaContent: Welcome to my place.
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  navTitleLink: /

menu:
  nav:
    - name: Blog
      url: /
      weight: 1
    - name: Tags
      url: /tags/
      weight: 2
    - name: About
      url: /about/
      weight: 3
    - name: RSS
      url: /index.xml
      weight: 4

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
